name: PHP Composer

on:
  push:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3  
   
    - name: dependencias
      # You may pin to the exact commit or the version.
      # uses: rethab/bash-action@8d1f7b182b1a1b00759f7ae1b67d5afb2a3494e9
      uses: rethab/bash-action@v1
      with:
        command: |
          apt-get install -y curl php7.4-cli php7.4-mbstring  phpunit php7.4 php7.4-common php7.4-opcache php7.4-mcrypt php7.4-cli php7.4-gd php7.4-curl php7.4-mysql php7.4-xml php7.4-intl php7.4-intl php7.4-mbstring php7.4-zip php7.4-mbstring php7.4-xdebug

    - name: composer
      # You may pin to the exact commit or the version.
      # uses: rethab/bash-action@8d1f7b182b1a1b00759f7ae1b67d5afb2a3494e9
      uses: rethab/bash-action@v1
      with:
        command: |
          wget https://getcomposer.org/installer -O composer-setup.php
          COMPOSER=906a84df04cea2aa72f40b5f787e49f22d4c2f19492ac310e8cba5b96ac8b64115ac402c8cd292b8a03482574915d1a8
          php -r "if (hash_file('SHA384', 'composer-setup.php') === '$COMPOSER') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
          php composer-setup.php --install-dir=/usr/local/bin --filename=composer
          composer update
          composer require cviebrock/eloquent-sluggable
          composer install
        
    - name: UT
      # You may pin to the exact commit or the version.
      # uses: rethab/bash-action@8d1f7b182b1a1b00759f7ae1b67d5afb2a3494e9
      uses: rethab/bash-action@v1
      with:
        command: |
          export XDEBUG_MODE=coverage
          vendor/bin/phpunit
          vendor/bin/phpunit --log-junit junit.xml
          vendor/bin/phpunit --coverage-clover coverage-report.xml

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      with:
        files: "**/junit.xml"

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
