name: PHP Composer

on:
  push:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3     
    - uses: actions/github-script@v6
      id: compose
      with:
        script: |
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            COMPOSER=906a84df04cea2aa72f40b5f787e49f22d4c2f19492ac310e8cba5b96ac8b64115ac402c8cd292b8a03482574915d1a8
            php -r "if (hash_file('SHA384', 'composer-setup.php') === '$COMPOSER') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
            php composer-setup.php --install-dir=/usr/local/bin --filename=composer

            composer update
            composer require cviebrock/eloquent-sluggable
            composer install
        result-encoding: string
    
    - uses: actions/github-script@v6
      id: test
      with:
        script: |
          export XDEBUG_MODE=coverage
          vendor/bin/phpunit
          vendor/bin/phpunit --log-junit junit.xml
          vendor/bin/phpunit --coverage-clover coverage-report.xml
        result-encoding: string
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      with:
        files: "**/junit.xml"

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
