name: PHP Composer

on:
  push:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3     
    - name: composer
      # You may pin to the exact commit or the version.
      # uses: rethab/bash-action@8d1f7b182b1a1b00759f7ae1b67d5afb2a3494e9
      uses: rethab/bash-action@v1
      with:
        command: |
          composer install
        
    - name: UT
      # You may pin to the exact commit or the version.
      # uses: rethab/bash-action@8d1f7b182b1a1b00759f7ae1b67d5afb2a3494e9
      uses: rethab/bash-action@v1
      with:
        command: |
          export XDEBUG_MODE=coverage
          vendor/bin/phpunit
          vendor/bin/phpunit --log-junit junit.xml
          vendor/bin/phpunit --coverage-clover coverage-report.xml

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      with:
        files: "**/junit.xml"

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
